name: Build Windows Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows Binaries on Windows Latest
    runs-on: windows-latest

    steps:
    - name: Cancel previous runs on the same branch
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set git urls to https instead of ssh
      run: |
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}\build

    - name: Configure CMake
      working-directory: ${{github.workspace}}\build
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE="Release"

    - name: Build Windows binaries with make_msvc.bat
      working-directory: ${{github.workspace}}\build
      run: |
        cmake --build build -- -k0
        ls ${{ github.workspace }}\build\

    - name: Upload Windows binaries to artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: chia-plot-sink.exe
        path: ${{ github.workspace }}\build\

    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag-name
      run: |
        echo "::set-output name=TAG_NAME::$(echo ${{ github.ref }} | cut -d'/' -f 3)"
        echo "::set-output name=REPO_NAME::$(echo ${{ github.repository }} | cut -d'/' -f 2)"